Development time
NiTro005/OOP-Work pull request #1
Opened 2024-03-05 14:44 UTC by NiTro005

*был создан файл

2024-03-05 14:45 UTC, NiTro005 commented
@UsovaMA проверьте пожалуйста

2024-03-05 14:48 UTC, NiTro005 reviewed
Все очень хорошо

2024-03-05 14:48 UTC, NiTro005 commented
👍

2024-03-05 14:49 UTC, NiTro005 commented
👍

2024-03-05 16:34 UTC, NiTro005 reviewed
Ничего не понятно

2024-03-07 17:43 UTC, NiTro005 commented
@bizi2 , @AtikD оцените

2024-03-07 19:24 UTC, AtikD commented
> @bizi2 , @AtikD оцените

а что оценивать, кроме конструкторов и ошибки в указателяъ ничего нет

2024-03-07 19:27 UTC, AtikD requested changes
нет ничего кроме конструкторов емае

2024-03-07 19:27 UTC, AtikD commented on OOP-projects/CTime/ctime.h
> +	CTime(const CTime& time);
указатели в аргументах через *, ты пытаешься получить указатель указателя?.....

2024-03-10 21:10 UTC, NiTro005 commented
@AtikD , @bizi2, @milksos, @kaur42 оцените

2024-03-11 11:18 UTC, bizi2 reviewed
ошибок не заметил , 👍

2024-03-11 11:18 UTC, milksos commented
Вроде всё нормально

2024-03-11 11:20 UTC, milksos commented
:+1

2024-03-11 11:22 UTC, kaur41 commented
все норм

2024-03-11 11:23 UTC, milksos commented
:+1:

2024-03-11 11:24 UTC, NiTro005 commented
@UsovaMA проверьте

2024-03-11 11:33 UTC, AtikD requested changes
так дела не делаются

2024-03-11 11:33 UTC, AtikD commented on OOP-projects/CTime/ctime.cpp
> +CTime::~CTime() {}
зачем тебе деструктор, все равно пустой ведь

2024-03-11 11:33 UTC, AtikD commented on OOP-projects/CTime/ctime.h
>  	CTime(const CTime& time);
ты все еще не заменил & на * ////////

2024-03-11 11:33 UTC, AtikD commented on OOP-projects/CTime/ctime.cpp
> +void output();
зачем ты это сделал??? ненужное объявление. check и CTime::check это две разные функции

2024-03-11 11:33 UTC, AtikD commented on OOP-projects/CTime/ctime.cpp
> +int compare(const CTime& time);
к остальному коммент о ненужном объявлении тоже относится

2024-03-11 11:33 UTC, AtikD commented on OOP-projects/CTime/ctime.cpp
> +void CTime::assign(CTime& time) {
вместо & ставится *...

2024-03-11 11:49 UTC, NiTro005 commented on OOP-projects/CTime/ctime.cpp
> +CTime::~CTime() {}
Потому что сказали шаблонно всегда писать все конструкторы, сэттеры и деструктор, даже если не используешь

2024-03-11 11:49 UTC, NiTro005 commented on OOP-projects/CTime/ctime.h
>  	CTime(const CTime& time);
Мы пишем на С++, надо пользоваться особенностями языка

2024-03-11 11:53 UTC, NiTro005 commented on OOP-projects/CTime/ctime.cpp
> +int compare(const CTime& time);
исправил

2024-03-11 19:11 UTC, felipenunezz commented
хороший код 👌👌

2024-04-02 11:56 UTC, UsovaMA commented
@NiTro005 👍

2024-04-02 11:58 UTC, merged